---
title: "Documentation_Groupproject_BSL"
output:
  html_document: default
  pdf_document: default
date: "December 8, 2017"
---

```
```

## Project title: **Obesity Induced Changes in Gene Expression**
## Group partners: Shane Davitt, Bhavana Palakurthi, Lindsay Serene
## Scripting Language: R
## Teaching Assistant: Ann Raiho

### *Tasks due prior to class, 29 November 2017:*

1. Use BLAST to identify the genes encoded by the 6 differentially expressed transcripts listed in uniquetranscripts.fasta *(Lindsay)*
2. Search the NCBI protein database (Nucleotide collection (nr/nt) Database) for amino acid sequences corresponding to these 6 transcripts *(Lindsay)*
3. Translate the 4 provided files of "RNAseq data". Write a R script to translate nucleotide sequences into amino acid sequences *(Pseudocode by Shane and Bhavana)*

### *Tasks in class, 29 November 2017:*

4. Translate pseudo code into R code. *(All three)*
5. Translating using grep, substring, and while loop. *(Lindsay)*
6. Translating using regex and translate function. *(Bhavana)*


### *Tasks due by the end of class, 1 December 2017:*

7. Translate pseudo code into R code. *(Lindsay and Bhavana)*
8. Build a Hidden Markov Model for each of the 6 transcript proteins and search the 4 translated "RNAseq files". *(All the three)*

### *Tasks due prior to class, 6 December 2017:*

9. Documentation of the project plan. *(Bhavana)*
10. Translate pseudo code into R code. *(Lindsay and Bhavana)*


### *Tasks in class, 6 December 2017:*

11. Translate pseudo code into R code. *(Lindsay and Bhavana)*
12. Compare and discuss the code for translating RNAseq data and choose the best and efficient code. *(All the three)*
13. Peer review of the code. *(All the three)*

### *Tasks due prior to class, 8 December 2017:*

14. Translate pseudo code into R code. *(Lindsay and Bhavana)*
15. Further exploration 1:Examine how discontinuous megablast and blastn qualitatively change your table of BLAST hits. *(Shane)* 
16. Further exploration 2: Explore the effects of phylogenetic relatedness of amino acid sequences on the performance of the HMM mode. *(Lindsay and Bhavana)*
17. Make changes as per discussion and peer review on the final code. *(All the three)*
18. Comment collectively on the final code for all the sub-problems.*(All the three)*
16. Final check to make sure all the files are uploaded to github. *(All the three)*

### *Tasks due before deadline, noon of 8, December 2017:*

19. Submission of the url for the github repo for the group project emailed to TA.*(All the three)*

```
```


```
```

